// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "my-currency-service/currency/internal/dto"

	mock "github.com/stretchr/testify/mock"

	repository "my-currency-service/currency/internal/repository"
)

// CurrencyService is an autogenerated mock type for the CurrencyService type
type CurrencyService struct {
	mock.Mock
}

// GetCurrencyRatesInInterval provides a mock function with given fields: ctx, reqDTO
func (_m *CurrencyService) GetCurrencyRatesInInterval(ctx context.Context, reqDTO *dto.CurrencyRequestDTO) ([]repository.CurrencyRate, error) {
	ret := _m.Called(ctx, reqDTO)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrencyRatesInInterval")
	}

	var r0 []repository.CurrencyRate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CurrencyRequestDTO) ([]repository.CurrencyRate, error)); ok {
		return rf(ctx, reqDTO)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CurrencyRequestDTO) []repository.CurrencyRate); ok {
		r0 = rf(ctx, reqDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.CurrencyRate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CurrencyRequestDTO) error); ok {
		r1 = rf(ctx, reqDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCurrencyService creates a new instance of CurrencyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCurrencyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CurrencyService {
	mock := &CurrencyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
