// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "my-currency-service/currency/internal/dto"

	mock "github.com/stretchr/testify/mock"

	repository "my-currency-service/currency/internal/repository"
)

// CurrencyService is an autogenerated mock type for the CurrencyService type
type CurrencyService struct {
	mock.Mock
}

type CurrencyService_Expecter struct {
	mock *mock.Mock
}

func (_m *CurrencyService) EXPECT() *CurrencyService_Expecter {
	return &CurrencyService_Expecter{mock: &_m.Mock}
}

// GetCurrencyRatesInInterval provides a mock function with given fields: ctx, reqDTO
func (_m *CurrencyService) GetCurrencyRatesInInterval(ctx context.Context, reqDTO *dto.CurrencyRequestDTO) ([]repository.CurrencyRate, error) {
	ret := _m.Called(ctx, reqDTO)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrencyRatesInInterval")
	}

	var r0 []repository.CurrencyRate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CurrencyRequestDTO) ([]repository.CurrencyRate, error)); ok {
		return rf(ctx, reqDTO)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CurrencyRequestDTO) []repository.CurrencyRate); ok {
		r0 = rf(ctx, reqDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.CurrencyRate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CurrencyRequestDTO) error); ok {
		r1 = rf(ctx, reqDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CurrencyService_GetCurrencyRatesInInterval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrencyRatesInInterval'
type CurrencyService_GetCurrencyRatesInInterval_Call struct {
	*mock.Call
}

// GetCurrencyRatesInInterval is a helper method to define mock.On call
//   - ctx context.Context
//   - reqDTO *dto.CurrencyRequestDTO
func (_e *CurrencyService_Expecter) GetCurrencyRatesInInterval(ctx interface{}, reqDTO interface{}) *CurrencyService_GetCurrencyRatesInInterval_Call {
	return &CurrencyService_GetCurrencyRatesInInterval_Call{Call: _e.mock.On("GetCurrencyRatesInInterval", ctx, reqDTO)}
}

func (_c *CurrencyService_GetCurrencyRatesInInterval_Call) Run(run func(ctx context.Context, reqDTO *dto.CurrencyRequestDTO)) *CurrencyService_GetCurrencyRatesInInterval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.CurrencyRequestDTO))
	})
	return _c
}

func (_c *CurrencyService_GetCurrencyRatesInInterval_Call) Return(_a0 []repository.CurrencyRate, _a1 error) *CurrencyService_GetCurrencyRatesInInterval_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CurrencyService_GetCurrencyRatesInInterval_Call) RunAndReturn(run func(context.Context, *dto.CurrencyRequestDTO) ([]repository.CurrencyRate, error)) *CurrencyService_GetCurrencyRatesInInterval_Call {
	_c.Call.Return(run)
	return _c
}

// NewCurrencyService creates a new instance of CurrencyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCurrencyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CurrencyService {
	mock := &CurrencyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
