// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "my-currency-service/currency/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// CurrencyClient is an autogenerated mock type for the CurrencyClient type
type CurrencyClient struct {
	mock.Mock
}

type CurrencyClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CurrencyClient) EXPECT() *CurrencyClient_Expecter {
	return &CurrencyClient_Expecter{mock: &_m.Mock}
}

// FetchCurrentRates provides a mock function with given fields: ctx, req
func (_m *CurrencyClient) FetchCurrentRates(ctx context.Context, req *dto.CurrencyRequestDTO) (map[string]float64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FetchCurrentRates")
	}

	var r0 map[string]float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CurrencyRequestDTO) (map[string]float64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CurrencyRequestDTO) map[string]float64); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CurrencyRequestDTO) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CurrencyClient_FetchCurrentRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchCurrentRates'
type CurrencyClient_FetchCurrentRates_Call struct {
	*mock.Call
}

// FetchCurrentRates is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.CurrencyRequestDTO
func (_e *CurrencyClient_Expecter) FetchCurrentRates(ctx interface{}, req interface{}) *CurrencyClient_FetchCurrentRates_Call {
	return &CurrencyClient_FetchCurrentRates_Call{Call: _e.mock.On("FetchCurrentRates", ctx, req)}
}

func (_c *CurrencyClient_FetchCurrentRates_Call) Run(run func(ctx context.Context, req *dto.CurrencyRequestDTO)) *CurrencyClient_FetchCurrentRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.CurrencyRequestDTO))
	})
	return _c
}

func (_c *CurrencyClient_FetchCurrentRates_Call) Return(_a0 map[string]float64, _a1 error) *CurrencyClient_FetchCurrentRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CurrencyClient_FetchCurrentRates_Call) RunAndReturn(run func(context.Context, *dto.CurrencyRequestDTO) (map[string]float64, error)) *CurrencyClient_FetchCurrentRates_Call {
	_c.Call.Return(run)
	return _c
}

// NewCurrencyClient creates a new instance of CurrencyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCurrencyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CurrencyClient {
	mock := &CurrencyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
