// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "my-currency-service/currency/internal/dto"

	mock "github.com/stretchr/testify/mock"

	repository "my-currency-service/currency/internal/repository"

	time "time"
)

// ExchangeRateRepository is an autogenerated mock type for the ExchangeRateRepository type
type ExchangeRateRepository struct {
	mock.Mock
}

type ExchangeRateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ExchangeRateRepository) EXPECT() *ExchangeRateRepository_Expecter {
	return &ExchangeRateRepository_Expecter{mock: &_m.Mock}
}

// FindInInterval provides a mock function with given fields: ctx, _a1
func (_m *ExchangeRateRepository) FindInInterval(ctx context.Context, _a1 *dto.CurrencyRequestDTO) ([]repository.CurrencyRate, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindInInterval")
	}

	var r0 []repository.CurrencyRate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CurrencyRequestDTO) ([]repository.CurrencyRate, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CurrencyRequestDTO) []repository.CurrencyRate); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.CurrencyRate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CurrencyRequestDTO) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExchangeRateRepository_FindInInterval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindInInterval'
type ExchangeRateRepository_FindInInterval_Call struct {
	*mock.Call
}

// FindInInterval is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *dto.CurrencyRequestDTO
func (_e *ExchangeRateRepository_Expecter) FindInInterval(ctx interface{}, _a1 interface{}) *ExchangeRateRepository_FindInInterval_Call {
	return &ExchangeRateRepository_FindInInterval_Call{Call: _e.mock.On("FindInInterval", ctx, _a1)}
}

func (_c *ExchangeRateRepository_FindInInterval_Call) Run(run func(ctx context.Context, _a1 *dto.CurrencyRequestDTO)) *ExchangeRateRepository_FindInInterval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.CurrencyRequestDTO))
	})
	return _c
}

func (_c *ExchangeRateRepository_FindInInterval_Call) Return(_a0 []repository.CurrencyRate, _a1 error) *ExchangeRateRepository_FindInInterval_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExchangeRateRepository_FindInInterval_Call) RunAndReturn(run func(context.Context, *dto.CurrencyRequestDTO) ([]repository.CurrencyRate, error)) *ExchangeRateRepository_FindInInterval_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, date, baseCurrency, rates
func (_m *ExchangeRateRepository) Save(ctx context.Context, date time.Time, baseCurrency string, rates map[string]float64) error {
	ret := _m.Called(ctx, date, baseCurrency, rates)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, string, map[string]float64) error); ok {
		r0 = rf(ctx, date, baseCurrency, rates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExchangeRateRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type ExchangeRateRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - date time.Time
//   - baseCurrency string
//   - rates map[string]float64
func (_e *ExchangeRateRepository_Expecter) Save(ctx interface{}, date interface{}, baseCurrency interface{}, rates interface{}) *ExchangeRateRepository_Save_Call {
	return &ExchangeRateRepository_Save_Call{Call: _e.mock.On("Save", ctx, date, baseCurrency, rates)}
}

func (_c *ExchangeRateRepository_Save_Call) Run(run func(ctx context.Context, date time.Time, baseCurrency string, rates map[string]float64)) *ExchangeRateRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(string), args[3].(map[string]float64))
	})
	return _c
}

func (_c *ExchangeRateRepository_Save_Call) Return(_a0 error) *ExchangeRateRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExchangeRateRepository_Save_Call) RunAndReturn(run func(context.Context, time.Time, string, map[string]float64) error) *ExchangeRateRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewExchangeRateRepository creates a new instance of ExchangeRateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExchangeRateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExchangeRateRepository {
	mock := &ExchangeRateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
