service:
  server_port: 8303
  env: "local"

api:
  base_url: "https://data-api.ecb.europa.eu/service/data/EXR/D.%s.%s.SP00.A?startPeriod=%s&endPeriod=%s"
  timeout_seconds: 10

database:
  host: "localhost"
  port: 5430
  user: "postgres_user"
  password: "postgres_password"
  name: "postgres_db"

worker:
  schedule: "@daily"
  currency_pair:
    base_currency: "USD"
    target_currency: "EUR"